/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlyquancafe;

import Controller.QLBanHangController;
import DataProvider.ConstantClass;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author HT
 */
public class pnlBaoCao extends javax.swing.JPanel {

   // private DefaultTableModel  TableModel;
    
    /**
     * Creates new form pnlQLNH
     */
    public pnlBaoCao() {
        initComponents();
        
        this.setSize(ConstantClass.WIDTH_OF_CONTENT_PANEL, ConstantClass.HEIGHT_OF_CONTENT_PANEL);
        
       
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BCmonth = new javax.swing.JButton();
        BCyear = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("BÁO CÁO THỐNG KÊ DOANH  THU");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chọn chức năng báo  cáo:");

        BCmonth.setText("Báo cáo doanh  thu theo  tháng");
        BCmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCmonthActionPerformed(evt);
            }
        });

        BCyear.setText("Bao cáo doanh thu theo năm");
        BCyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCyearActionPerformed(evt);
            }
        });

        jButton1.setText("Báo cáo doanh thu ngày");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BCyear, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(BCmonth, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(BCyear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BCmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCmonthActionPerformed
             try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "cafe", "cafe");
             JasperDesign jd=JRXmlLoader.load("F:\\u\\cafe\\QuanLyQuanCafe\\src\\Music\\report3.jrxml");
            JasperReport jr= JasperCompileManager.compileReport("F:\\u\\cafe\\QuanLyQuanCafe\\src\\Music\\report3.jrxml");
            JasperPrint jp=JasperFillManager.fillReport(jr, new HashMap(), conn);           // JasperPrint p=JasperFillManager.fillReport(report,map,Connection.);
            JasperViewer jv= new JasperViewer(jp,false);
            jv.setVisible(true);
        } catch (Exception ex) {
           // System.out.println(ex.getMessage());
           ex.printStackTrace();
        }
        

    }//GEN-LAST:event_BCmonthActionPerformed

    private void BCyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCyearActionPerformed
          try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection conn=(Connection)DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:orcl", "cafe", "cafe");
             JasperDesign jd=JRXmlLoader.load("F:\\u\\cafe\\QuanLyQuanCafe\\src\\Music\\report4.jrxml");
            JasperReport jr= JasperCompileManager.compileReport("F:\\u\\cafe\\QuanLyQuanCafe\\src\\Music\\report4.jrxml");
            JasperPrint jp=JasperFillManager.fillReport(jr, new HashMap(), conn);           // JasperPrint p=JasperFillManager.fillReport(report,map,Connection.);
            JasperViewer jv= new JasperViewer(jp,false);
            jv.setVisible(true);
        } catch (Exception ex) {
           // System.out.println(ex.getMessage());
           ex.printStackTrace();
        }
        

    }//GEN-LAST:event_BCyearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCmonth;
    private javax.swing.JButton BCyear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
